language: go

go:
  - 1.6
  - 1.7
  - tip

go_import_path = github.com/doriable/yascat

install:
    - go get -v .
    - go get -v github.com/golang/lint/golint

script:
    - go vet -x ./...
    - golint ./...
    - go test -v ./...
